Python: Fix return_value_policy error in DigitalTopology
In `foreground()`, and `background()` methods.
These `MetricAdjacency` members are references and non-copyable.

```
RuntimeError: return_value_policy = copy, but type DGtal::MetricAdjacency<DGtal::SpaceND<2u, int>, 2u, 2u> is non-copyable!
```

Set `py::return_value_policy::reference_internal` instead of automatic (it was doing copies)